name: racha_conta
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uuid: ^4.0.0
  gap: ^3.0.1 
  intl: ^0.18.1
  flutter_config: ^2.0.2
  get: ^4.6.6
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_storage: ^11.4.1
  cloud_firestore: ^4.12.2
  google_sign_in: ^6.1.5
  flutter_native_splash: ^2.3.5
  line_awesome_flutter: ^2.0.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
